from os import environ as env


class Config:
    EMAIL_PASSWORD = env["EMAIL_PASSWORD"]
    SECRET_KEY = env["SECRET_KEY"]
    WIALON_HOSTING_API_TOKEN = env["WIALON_HOSTING_API_TOKEN"]
    SPREADSHEET_ID = env["SPREADSHEET_ID"]

    TWILIO_SID = env["TWILIO_SID"]
    TWILIO_SECRET = env["TWILIO_SECRET"]
    TWILIO_TOKEN = env["TWILIO_TOKEN"]

    # LIGHT_METRICS_AUTH_CODE = env["LIGHT_METRICS_AUTH_CODE"]
    # LIGHTMETRICS_USERNAME = env["LIGHTMETRICS_USERNAME"]
    # LIGHTMETRICS_PASSW = env["LIGHTMETRICS_PASSW"]
