from os import environ as env


class Config:
    EMAIL_PASSWORD = env["EMAIL_PASSWORD"]
    SECRET_KEY = env["SECRET_KEY"]
    WIALON_HOSTING_API_TOKEN = env["WIALON_HOSTING_API_TOKEN"]
    SPREADSHEET_ID = env["SPREADSHEET_ID"]

    TWILIO_SID = env["TWILIO_SID"]
    TWILIO_SECRET = env["TWILIO_SECRET"]
    TWILIO_TOKEN = env["TWILIO_TOKEN"]

    QB_CLIENT_ID = env["QB_CLIENT_ID"]
    QB_CLIENT_SECRET = env["QB_CLIENT_SECRET"]
    QB_ACCESS_TOKEN = env["QB_ACCESS_TOKEN"]
